### ISSUE TITLE
Rust version

### ISSUE THREAD

**Issue by prem-prakash** [spruceid/siwe-ex#14]
Can you clarify the rust version needed? Tried to compile it worked with 1.56.0 but not 1.55.0.
Is that correct?

**Comment by krhoda** [comment]
Yes, the minimum is going to be `1.56.0` because some of the dependencies of [siwe-rs]() use Rust edition 2021 and `1.56.0` is the earliest compiler that supports it. I've added information in PR #13 to the README to reflect this.
