### ISSUE TITLE
Hex package does not contain native directory

### ISSUE THREAD

**Issue by prem-prakash** [spruceid/siwe-ex#17]
It looks like the native directory is not being uploaded to hex.pm.

The only way I can get it is if I specify the github repo (`{:siwe, "~> 0.3.2", git: "https://github.com/spruceid/siwe-ex", branch: "main"},` and then mix will download the dep directly from github.

As per documentation https://hex.pm/docs/publish it looks like it is not possible to use git submodules.

But some other libs are doing it.

It may be needed to specify the files, like here:

https://github.com/omgnetwork/ex_secp256k1/blob/master/mix.exs

**Comment by krhoda** [comment]
Thank you for the example! Fix with PR #18 just use version `0.4.0` and the native directory is there.
